add_newline=true

[package]
disabled=true

[aws]
disabled=true

# [conda]
# ignore_base = false
# symbol="conda->"
# format = "[$symbol$environment ](bold dimmed green)"

[python]
symbol = '👾 '

[shell]
style= "gray bold"
disabled = false

[git_status]
disabled=true

[battery]
charging_symbol = '⚡️ '
empty_symbol = '💀 '

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'bold red'

